name: Databricks Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write    # Required for OIDC
  contents: read     # Required to checkout code

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install Databricks CLI
        uses: databricks/setup-cli@v0.2.0

      - name: Deploy Bundle
        run: |
          databricks bundle deploy -t prod

bundle:
  name: my_data_pipeline  # 🏷️ Give your project a name

targets:
  dev:                    # 🧪 For your sandbox/testing
    workspace:
      host: https://adb-7405614454563413.13.azuredatabricks.net
  
  prod:                   # 🚀 For your production environment
    workspace:
      host: https://adb-7405614454563413.13.azuredatabricks.net
    # You can override cluster settings or schedules here for production